[theme]
primaryColor = "#0B5745"
backgroundColor = "#F4F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14231F"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
